- name: Example jinja2 AS3 template
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  
## Playbook Vars Here 
  vars:
    VIRTUALS:
      - name: "example1"
        virtualAddresses: "10.0.1.10"
        default_pool: "web_pool1"
    POOLS:
      - name: "web_pool1"
        servicePort: 80
        serverAddresses: 
          - "192.0.1.10"
          - "192.0.1.11"

  tasks:
    
    - name: load shared vars
      include_vars:
        example4.shared-vars.yml

    - name: Build AS3 declaration in files/example4-AS3.json
      template:
        src: "{{ playbook_dir }}/templates/example4.j2"
        dest: "{{ playbook_dir }}/files/example4-AS3.json"